config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'offers' => 'offers/offers#index'
  end

  devise_for :admins , controllers: {
    sessions: 'admins/sessions'
  },
  path: "/",
  path_names: { sign_in: 'admin/login',
                sign_out: 'admin/logout',
              }
  devise_scope :admin do
    authenticated :admin do
      resources :offers, only: [:update]
      #ver lista de ofertas
      get '/ofertas' => 'offers#index', as: :offers
      
      #criar oferta
      post '/ofertas' => 'offers#create', as: :new_offer
      
      #editar oferta
      get '/oferta/:id/editar' => 'offers#edit', :as => 'edit_offer'
      
      #arquivar oferta
      put '/oferta/:id/arquivar' => 'offers#archive', :as => 'archive_offer'
      
      #ver lista de ofertas arquivadas
      get '/ofertas/arquivadas' => 'offers#archived_list', as: :archived_list

      resources :admins, only: [:destroy, :update, :edit, :delete]
      
      get '/admin/cadastro', to: 'admins#new'
      post '/admin/cadastro' => 'admins#create', as: :new_admin
      
      root  'offers#index',  as: :authenticated_admin_root

      get 'admins' => 'admins#index'
    end
  end
  root  'offers#index',  as: :unauthenticated_admin_root
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :name, :email, :password, :permission_level       
  enum permission_level: { 'Criar': 0, 'Criar-Editar': 1 , 'Administrador': 2}
  
  def self.has_default?
    Admin.all.each do |admin|
      admin.is_default == true ? true : false
    end
  end   
  def has_permission?
    return self.permission_level == "Criar-Editar" || self.permission_level == "Administrador" ? true : false
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/offer.rb
class Offer < ApplicationRecord
    validates_presence_of :title, :description, :price
    validates :price,
    numericality: { greater_than: 0, message: "A número deve ser maior que zero." }

    def self.filter_by_archived(archived)
        unless archived.nil?
            @offers = Offer.where(archived: archived)
        end
    end
    def self.filter_by_admin(admin)
        unless admin.nil?
            @offers = Offer.all().where(created_by: admin) 
        end
    end
    
    def as_json(options = {})
        super(options.merge({ except: [:created_at,:updated_at] }))
    end
end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  layout 'admin_login'
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  
    def after_sign_in_path_for(admin)
      authenticated_admin_root_path
    end
  
    # Overwriting the sign_out redirect path method
    def after_sign_out_path_for(resource_or_scope)
      new_admin_session_path
    end
  
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins_controller.rb
class AdminsController <  ApplicationController
    before_action :require_default_admin
    before_action :authenticate_admin!
    before_action :get_admin, only: [:destroy, :edit, :update]

    layout 'dashboard'

    def index
        @admins = Admin.all
    end

    def new
        @admins = Admin.new
      end
    
    def create
        @admin = Admin.new(admin_params)
        if @admin.save
            redirect_to admins_path, notice: "Admin criado com sucesso."
        else
            redirect_to new_admin_path, notice: 'Erro' 
        end
    end

    def update
        if @admin.update(admin_params)
          redirect_to  admins_path, notice: 'Atualizado com sucesso'
        else
          redirect_to  admins_path, notice: 'Erro'
        end
    end
    
    def destroy
        name = @admin.name
        @admin.destroy
        if @admin.destroy
            redirect_to admins_path, notice: "O administrador #{name} foi excluído."
        else
            redirect_to admins_path, notice: "Não foi possível excluir o administrador #{name}."
        end
    end

    private

    def admin_params
        params.require(:admin).permit(:name, :email, :password, :is_default, :permission_level, :avatar)
    end

    def get_admin
        @admin = Admin.find(params[:id])
    end

    def require_default_admin
       unless current_admin.is_default == true
         redirect_to admins_path, notice: 'Erro'
       end
     end
end

app/controllers/api/offers/offers_controller.rb
class API::Offers::OffersController < ApplicationController

    def index
        @offers = Offer.all()

        archived  = params[:archived] ? params[:archived]  : nil
        admin = params[:admin] ? params[:admin] : nil

        if archived != nil 
            offers = Offer.filter_by_archived(archived)
            render :status => 200, :json => {success: true, data: offers } 
            
        elsif admin != nil
            offers = Offer.filter_by_admin(admin)
            render :status => 200, :json => {success: true, data: offers } 
        else
            render :status => 200, :json => {success: true, data: @offers }
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_admin!
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
    layout "dashboard"
    before_action :authenticate_admin!
  end

app/controllers/offers_controller.rb
class OffersController < BaseController
  before_action :check_permission, only: [:edit, :update]
  before_action :set_offer, only: [:show, :edit, :update, :archive]

  def index
    @offers = Offer.all.where.not(:archived => true).order('created_at DESC').paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.html
      format.js
    end
    @offer = Offer.new
  end
  
  def archived_list
    @offers = Offer.all.where(:archived => true)
  end

  def new
  end

  def edit
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.created_by = current_admin.email
    respond_to do |format|
      if @offer.save
        format.html { redirect_to @offer, notice: 'Oferta criada com sucesso!' }
        format.js
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.js
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to offers_path, notice: 'Oferta atualizada com sucesso!.' }
      else
        format.html { render :edit }
      end
    end
  end

  def archive
    @offer.update_attributes(:archived => true, :archived_at => Time.now())
    redirect_to archived_list_path
  end

  private
  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:title, :description, :avatar, :price, :created_by, :archived, :archived_at)
  end
  
  #checa se o admin possui permissão para editar
  def check_permission
    unless current_admin.has_permission?
      redirect_to offers_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_message
        messages = ""
        [:notice, :info, :warning, :error].each {|type|
          if flash[type]
            messages += "#{flash[type]}"
          end
        }
        messages
      end
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/admins/edit.html.erb
<div class="margin-top-5">
        <div class="container-fluid">
          <div class="row justify-center margin-top">
          <div class="col-md-8">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title">Editar</h4>
              </div>
              <div class="card-body">
                  <%= form_for @admin, url: {action: "update"} do |f| %>
                  <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :name, class:"bmd-label-floating" do %>
                          Nome
                          <% end %>
                          <%= f.text_field :name, autofocus: true, class:"form-control" %>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :email, class:"bmd-label-floating" %>
                          <%= f.email_field :email, autofocus: true, class:"form-control" %>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-6">
                        <div class="form-group justify-between">
                            <%= f.select(:permission_level, ["Criar", "Criar-Editar"], {},  {:class => 'form-control'}) %>
                            <i class="material-icons select-icon">expand_more</i>
                        </div>
                      </div>
                  </div>
                  <div class="row justify-center">
                    <%= f.submit "Editar Assistente", class:"btn btn-primary pull-right" %>
                  </div>
                  <div class="clearfix"></div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    

app/views/admins/index.html.erb
<div class="margin-top-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="card">
                    <div class="card-header card-header-tabs card-header-primary">
                        <div class="nav-tabs-navigation">
                            <div class="nav-tabs-wrapper justify-between">
                                <span class="nav-tabs-title">Gerenciamento de Assistentes</span>
                                <ul class="nav nav-tabs" data-tabs="tabs">
                                    <li class="nav-item">
                                        <%= link_to(new_admin_path, class:"nav-link active") do %>
                                        <i class="material-icons">add</i> Adicionar Novo
                                        <div class="ripple-container"></div>
                                        <% end %>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="card-body table-responsive">
                        <table class="table table-hover">
                        <thead class="text-warning">
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Permissões</th>
                            <th><%= @teste %></th>
                        </thead>
                        <tbody>
                            <% @admins.each do |admin| %>
                                <tr>
                                <% if admin.is_default == false %>
                                    <td><%= admin.id %></td>
                                    <td><%= admin.name %></td>
                                    <td><%= admin.email %></td>
                                    <td><%= admin.permission_level %></td>
                                    <td class="td-actions text-right">
                                        <%= link_to edit_admin_path(admin), rel:"tooltip", title:"Editar", class:"btn btn-primary btn-link btn-sm" do %>
                                            <i class="material-icons">edit</i>
                                        <% end %>
                                    </td>
                                    <td>
                                        <%= button_to admin, method: :delete , rel:"tooltip", title:"Remover", class:"btn btn-danger btn-link btn-sm", data: { confirm: "Deseja realmente apagar o administrador #{admin.name}" } do %>
                                        <i class="material-icons">close</i>
                                        <% end %>
                                    </td>
                                </tr>
                                <% end %>
                            <% end %>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>   

app/views/admins/new.html.erb
<div class="margin-top-5">
        <div class="container-fluid">
          <div class="row justify-center margin-top">
          <div class="col-md-8">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title">Cadastro de assistentes</h4>
              </div>
              <div class="card-body">
                  <%= form_for @admins, url: {action: "create"} do |f| %>
                  <% if @admins.errors.any? %>
                    <ul>
                      <% @post.errors.full_messagens.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                    </ul>
                  <% end %>
                  <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :name, class:"bmd-label-floating" do %>
                          Nome
                          <% end %>
                          <%= f.text_field :name, autofocus: true, class:"form-control" %>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :email, class:"bmd-label-floating" %>
                          <%= f.email_field :email, autofocus: true, class:"form-control" %>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= f.label :password, class:"bmd-label-floating" do %>
                          Senha
                          <% end %>
                          <!-- <em>(<%= @minimum_password_length %> characters minimum)</em> -->
                          <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
                        </div>
                      </div>
                  </div>
                  <div class="row">
                      <div class="col-md-6">
                        <div class="form-group justify-between">
                            <%= f.select(:permission_level, ["Permissão", "Criar", "Criar-Editar"], {required: true, selected: 'Permissão', disabled: 'Permissão'},  {:class => 'form-control'}) %>
                            <i class="material-icons select-icon">expand_more</i>
                        </div>
                      </div>
                  </div>
                  <div class="row justify-center">
                    <%= f.submit "Criar Assistente", class:"btn btn-primary pull-right" %>
                  </div>
                  <div class="clearfix"></div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    

app/views/layouts/admin_login.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
   <head>
      <title>Big Offers</title>
      <%= csrf_meta_tags %>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="language" content="pt-BR" />
      <link rel="icon" type="image/png" sizes="16x16" href="#">
      <meta name="description" content="Plataforma de ofertas" />
      <meta name="keywords" content="advogado cliente justica">
      <%= stylesheet_link_tag  'dashboard', media: 'all', 'data-turbolinks-track' => true %>
      <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
   </head>
   <body>
    <%= yield %>
    <%= javascript_include_tag 'dashboard' %>
   </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Big Offers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
   <head>
      <title>Big Offers</title>
      <%= csrf_meta_tags %>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="language" content="pt-BR" />
      <link rel="icon" type="image/png" sizes="16x16" href="#">
      <meta name="description" content="Plataforma de ofertas" />
      <meta name="keywords" content="advogado cliente justica">
      <%= stylesheet_link_tag  'dashboard', media: 'all', 'data-turbolinks-track' => true %>
      <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
   </head>
   <body>
    <% flash.each do |key, value| %>
    <script type="text/javascript">
        toastr.warning("<span><%= value %></span>", "Aviso");
    </script>
    <% end %>
    <%= render "layouts/shared/admin_shared" %>
    <%= javascript_include_tag 'dashboard' %>
   </body>
</html>

app/views/layouts/shared/_admin_shared.html.erb
<div class="wrapper ">
    <div class="sidebar" data-color="orange" data-background-color="white">
      <div class="logo">
        <a href="http://www.creative-tim.com" class="simple-text logo-normal">
          Big Offers Admin
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item active  ">
            <%= link_to(offers_path, class:"nav-link") do %>
              <i class="material-icons">dashboard</i>
              <p>Ofertas</p>
            <% end %>
          </li>
          <% if current_admin.is_default == true %>
            <li class="nav-item ">
              <%= link_to(admins_path, class:"nav-link") do %>
                <i class="material-icons">person</i>
                <p>Assistentes</p>
              <% end %>
            </li>
          <% end %>
          <% if admin_signed_in? %>
            <li class="nav-item ">
              <%= link_to(destroy_admin_session_path, :method => :delete, class:"nav-link")  do %> 
                <i class="material-icons">exit_to_app</i>
                <p>Sair</p>
              <% end %>
            </li>
          <% end %>          
        </ul>
      </div>
    </div>
    <div class="main-panel">
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
                <div class="container-fluid">
                  <div class="navbar-wrapper">
                    <a class="navbar-brand" href="#pablo"></a>
                  </div>
                  <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                    <span class="navbar-toggler-icon icon-bar"></span>
                  </button>
                  <div class="collapse navbar-collapse justify-content-end">
                    <ul class="navbar-nav">
                    </ul>
                  </div>
                </div>
              </nav>
              <!-- End Navbar -->
      <!-- End Navbar -->
      <%= yield %>
    </div>
  </div>

app/views/offers/_form.html.erb
<div class="margin-top-5">
<div class="container-fluid">
    <div class="row justify-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                <h4 class="card-title">Ofertas</h4>
                </div>
                <div class="card-body">
                    <%= form_for @offer, url: {action: "update"}  do |f| %>
                    <% if @offer.errors.any? %>
                    <script>
                        $(document).ready(function() {
                        noty({text: ' <%= pluralize(@offer.errors.count, "error") %> encontrados: </br><ul><% @offer.errors.each do |attr,message| %><li><%= message %></li><% end %></ul>', layout: 'bottom', type: 'warning', timeout: 4000});
                        });
                    </script>
                    <% end %>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <%= f.label :title, class:"bmd-label-floating" do %>
                                    Título
                                <% end %>
                                <%= f.text_field :title, autofocus: true, class:"form-control", id:"title" %>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <%= f.label :price, class:"bmd-label-floating" do %>
                                    Valor da Oferta
                                <% end %>
                                <%= f.text_field :price, autofocus: true, class:"form-control", id: "price" %>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                        <div class="form-group">
                            <%= f.label :description, class:"bmd-label-floating" do %>
                                Descrição
                            <% end %>
                            <%= f.text_field :description, autofocus: true, class:"form-control", id: "description" %>
                        </div>
                        </div>
                    </div>
                    <!-- <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <%= f.label :avatar, class:"bmd-label-floating" do %>
                                    Imagem da oferta
                                <% end %>
                                <%= f.file_field :avatar, class:"form-control"%>
                            </div>
                        </div>
                    </div> -->

                    <div class="row justify-center">
                    <%= f.submit "Editar", class:"btn btn-primary pull-right" %>
                    </div>
                    <div class="clearfix"></div>
                <% end %>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

app/views/offers/_offer.html.erb
<% if offer.archived == false %>
    <tr>
        <td><%= offer.id %></td>
        <td><%= offer.title %></td>
        <td><%= offer.price %></td>
        <td><%= offer.created_by %></td>
        <td><%= offer.created_at.strftime("%d/%m/%Y  %H:%M:%S")  %></td>
        <% if current_admin.has_permission? %>
            <td class="td-actions text-right">
                <%= link_to edit_offer_path(offer), rel:"tooltip", title:"Editar", class:"btn btn-primary btn-link btn-sm" do %>
                    <i class="material-icons">edit</i>
                <% end %>
            </td>
        <% end %>
        <td>
            <%= button_to archive_offer_path(offer), method: :put , rel:"tooltip", title:"Arquivar", class:"btn btn-green btn-link btn-sm" do %>
            <i class="material-icons">archive</i>
            <% end %>
        </td>
    </tr>
<% end %>

app/views/offers/archived_list.html.erb
<div class="margin-top-5">
    <div class="container-fluid">
            <div class="row">
                    <div class="col-lg-12 col-md-12">
                        <div class="card">
                            <div class="card-header card-header-tabs card-header-primary">
                                    <div class="nav-tabs-navigation">
                                        <div class="nav-tabs-wrapper justify-between">
                                            <span class="nav-tabs-title">Ofertas arquivadas(<%= @offers.count%>)</span>
                                        </div>
                                    </div>
                                </div>
                            <!-- <div class="row padding justify-end">
                                <div class="col-lg-4 col-md-4">
                                    <div class="input-group no-border">
                                        <input type="text" value="" class="form-control" placeholder="Pesquise...">
                                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                        <i class="material-icons">search</i>
                                        <div class="ripple-container"></div>
                                        </button>
                                    </div>
                                </div>
                            </div> -->
                            <div class="card-body table-responsive">
                                <table class="table table-hover">
                                <thead class="text-warning">
                                    <th>ID</th>
                                    <th>Título</th>
                                    <th>Preço</th>
                                    <th>Criado por</th>
                                    <th>Criado em</th>
                                    <th>Arquivado em</th>
                                </thead>
                                <tbody id="offers">
                                    <% @offers.each do |offer| %>
                                        <tr>
                                            <td><%= offer.id %></td>
                                            <td><%= offer.title %></td>
                                            <td><%= offer.price %></td>
                                            <td><%= offer.created_by %></td>
                                            <td><%= offer.created_at.strftime("%d/%m/%Y  %H:%M:%S")  %></td>
                                            <td><%= offer.archived_at.strftime("%d/%m/%Y  %H:%M:%S")  %></td>
                                        </tr>
                                    <% end %>
                                </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

app/views/offers/create.js.erb
$("<%= escape_javascript(render @offer) %>").prependTo("#offers");
$("#title").val("")
$("#description").val("")
$("#price").val("")

app/views/offers/edit.html.erb
<%= render 'form', offer: @offer %>

app/views/offers/index.js.erb
<%= infinite_append '#offers', @offers %>